# Generated by Django 3.1.7 on 2021-03-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='新任务', max_length=30)),
                ('task_type', models.CharField(choices=[('1', '通知'), ('2', '翻转课'), ('3', '作业'), ('4', '任务')], default='1', max_length=10)),
                ('content', models.TextField(default='发布了新的任务')),
                ('brief', models.TextField(default='任务描述')),
                ('allow_files', models.BooleanField(default=True)),
                ('due_time', models.DateField(default=None, null=True)),
            ],
        ),
    ]
