# Generated by Django 3.1.7 on 2021-03-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', '图片'), ('COMPRESS', '压缩包'), ('TEXT', '文本'), ('OTHER', '其他')], default='TEXT', max_length=30),
        ),
    ]
