# Generated by Django 3.1.7 on 2021-03-17 07:55

import TaskView.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0010_auto_20210317_1555'),
        ('TaskView', '0002_task_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', '图片'), ('COMPRESS', '压缩包'), ('TEXT', '文本'), ('AUDIO', '音频'), ('OTHER', '其他')], default='TEXT', max_length=30),
        ),
        migrations.CreateModel(
            name='UploadedTaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', TaskView.models.RestrictedFileField(upload_to='uploads/task/<django.db.models.query_utils.DeferredAttribute object at 0x10e8fe970>')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseView.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TaskView.task')),
            ],
        ),
    ]
