# Generated by Django 3.1.7 on 2021-03-18 05:51

import TaskView.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskView', '0004_auto_20210318_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedtaskfile',
            name='id',
        ),
        migrations.AddField(
            model_name='uploadedtaskfile',
            name='index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedtaskfile',
            name='file',
            field=TaskView.models.RestrictedFileField(upload_to='tasks/'),
        ),
    ]
