# Generated by Django 3.1.7 on 2021-03-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0011_auto_20210320_0112'),
        ('TaskView', '0006_auto_20210320_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedtaskfile',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='CourseView.user'),
        ),
        migrations.AlterField(
            model_name='uploadedtaskfile',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='TaskView.task'),
        ),
    ]
