# Generated by Django 3.1.7 on 2021-03-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='ID',
        ),
    ]
