# Generated by Django 3.1.7 on 2021-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0002_auto_20210311_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='同济大学的', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TE', 'Teacher'), ('ST', 'Student'), ('AD', 'Admin')], default='ST', max_length=2),
        ),
    ]
