# Generated by Django 3.1.7 on 2021-03-12 12:16

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0003_auto_20210311_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('time', models.TimeField(auto_now=True)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(default='未知章节', max_length=30)),
                ('subheading', models.CharField(default='快来学习吧！', max_length=50)),
                ('brief', models.TextField(default='点击开始学习')),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
