# Generated by Django 3.1.7 on 2021-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0004_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
