# Generated by Django 3.1.7 on 2021-03-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0005_auto_20210312_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
