# Generated by Django 3.1.7 on 2021-03-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0006_auto_20210312_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='新任务', max_length=30)),
                ('brief', models.TextField(default='任务描述')),
                ('allow_files', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='chapter',
            field=models.CharField(default='未知章', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='heading',
            field=models.CharField(default='未知节', max_length=30),
        ),
        migrations.CreateModel(
            name='Learns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseView.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseView.user')),
            ],
        ),
    ]
