# Generated by Django 3.1.7 on 2021-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0007_auto_20210313_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default='发布了新的任务'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('1', '通知'), ('2', '翻转课'), ('3', '作业'), ('4', '任务')], default='1', max_length=10),
        ),
    ]
