# Generated by Django 3.1.7 on 2021-03-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0008_auto_20210314_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
