# Generated by Django 3.1.7 on 2021-03-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0009_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
