# Generated by Django 3.1.7 on 2021-03-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseView', '0010_auto_20210317_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learns',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='CourseView.course'),
        ),
        migrations.AlterField(
            model_name='learns',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='CourseView.user'),
        ),
    ]
